
# Nama alur kerja yang akan muncul di GitHub Actions
name: Laravel CI

# Mendefinisikan kapan alur kerja akan dijalankan
on:
  push:
    # Ganti dengan branch utama Anda (misal: "main", "master", "develop")
    branches: [ "main", "master", "testing","iterasi1","iterasi2","iterasi3","iterasi4" ]
  pull_request:
    # Ganti dengan branch utama Anda (misal: "main", "master", "develop")
   branches: [ "main", "master", "testing","iterasi1","iterasi2","iterasi3","iterasi4" ]

# Sekumpulan pekerjaan yang akan dijalankan
jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: laravel_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: pdo_mysql, mbstring, dom, fileinfo, gd
        tools: composer

    - name: Create .env file and configure database
      # PENTING: Menggabungkan langkah pembuatan .env dan konfigurasi database
      # agar konfigurasi database sudah ada sebelum composer install selesai
      run: |
        cp .env.example .env
        # Menulis konfigurasi database langsung ke .env
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=laravel_test" >> .env
        echo "DB_USERNAME=root" >> .env
        echo "DB_PASSWORD=" >> .env
      working-directory: ./Src/Backend/Bussiness-travel # PATH LENGKAP KE FOLDER PROYEK LARAVEL ANDA

    - name: Install Composer dependencies
      # Composer install akan dijalankan setelah .env dikonfigurasi
      run: composer install --no-ansi --no-interaction --no-progress --prefer-dist
      working-directory: ./Src/Backend/Bussiness-travel

    - name: Generate application key
      run: php artisan key:generate
      working-directory: ./Src/Backend/Bussiness-travel

    - name: Run database migrations
      run: php artisan migrate --force
      working-directory: ./Src/Backend/Bussiness-travel

    - name: Run tests
      run: php artisan test
      working-directory: ./Src/Backend/Bussiness-travel
